// ════════════════════════════════════════════════════
//  QUESTION BANK — ~500 Q&A with 4-option multiple choice
//  Format: [category, question, correctAnswer, [wrong1, wrong2, wrong3]]
//  Answers are shuffled at runtime
// ════════════════════════════════════════════════════

const CATS = {
  EC: { name: 'Estados y Capitales', icon: '🗺️', color: '#1CB0F6' },
  GS: { name: 'Datos Generales y Símbolos', icon: '🦅', color: '#58CC02' },
  PH: { name: 'Época Prehispánica', icon: '🏛️', color: '#CE82FF' },
  CC: { name: 'Conquista y Colonia', icon: '⚔️', color: '#FF9600' },
  IN: { name: 'Independencia', icon: '🔔', color: '#FFC800' },
  RE: { name: 'Revolución', icon: '🎯', color: '#FF4B4B' },
  GT: { name: 'Geografía y Turismo', icon: '🌋', color: '#2EC4B6' },
  CG: { name: 'Civismo y Gobierno', icon: '🏛️', color: '#4D9BFF' },
  CE: { name: 'Ciencia, Educación y Deportes', icon: '🔬', color: '#58CC02' },
  LA: { name: 'Literatura, Arte y Cine', icon: '🎬', color: '#FF6B9D' },
  MF: { name: 'Música, Fiestas y Comida', icon: '🎶', color: '#F4B942' },
};

const RAW = [
// ── ESTADOS Y CAPITALES ──────────────────────────────────────────
['EC','¿Cuál es la capital de Aguascalientes?','Aguascalientes',['Tepic','Colima','Durango']],
['EC','¿Cuál es la capital de Baja California?','Mexicali',['Tijuana','Ensenada','La Paz']],
['EC','¿Cuál es la capital de Baja California Sur?','La Paz',['Los Cabos','Loreto','Mexicali']],
['EC','¿Cuál es la capital de Campeche?','Campeche',['Mérida','Chetumal','Villahermosa']],
['EC','¿Cuál es la capital de Chiapas?','Tuxtla Gutiérrez',['San Cristóbal de las Casas','Tapachula','Comitán']],
['EC','¿Cuál es la capital de Chihuahua?','Chihuahua',['Ciudad Juárez','Parral','Delicias']],
['EC','¿Cuál es la capital de Coahuila?','Saltillo',['Torreón','Monclova','Piedras Negras']],
['EC','¿Cuál es la capital de Colima?','Colima',['Manzanillo','Tecomán','Guadalajara']],
['EC','¿Cuál es la capital de Durango?','Durango',['Gómez Palacio','Lerdo','Nuevo Ideal']],
['EC','¿Cuál es la capital de Guanajuato?','Guanajuato',['León','Irapuato','Celaya']],
['EC','¿Cuál es la capital de Guerrero?','Chilpancingo',['Acapulco','Iguala','Taxco']],
['EC','¿Cuál es la capital de Hidalgo?','Pachuca',['Tulancingo','Tula','Ixmiquilpan']],
['EC','¿Cuál es la capital de Jalisco?','Guadalajara',['Puerto Vallarta','Zapopan','Lagos de Moreno']],
['EC','¿Cuál es la capital del Estado de México?','Toluca',['Ecatepec','Naucalpan','Tlalnepantla']],
['EC','¿Cuál es la capital de Michoacán?','Morelia',['Uruapan','Zamora','Lázaro Cárdenas']],
['EC','¿Cuál es la capital de Morelos?','Cuernavaca',['Cuautla','Jiutepec','Temixco']],
['EC','¿Cuál es la capital de Nayarit?','Tepic',['Bahía de Banderas','Compostela','Acaponeta']],
['EC','¿Cuál es la capital de Nuevo León?','Monterrey',['Guadalupe','Apodaca','San Nicolás de los Garza']],
['EC','¿Cuál es la capital de Oaxaca?','Oaxaca de Juárez',['Juchitán','Salina Cruz','Tehuantepec']],
['EC','¿Cuál es la capital de Puebla?','Puebla de Zaragoza',['Tehuacán','Atlixco','San Martín Texmelucan']],
['EC','¿Cuál es la capital de Querétaro?','Santiago de Querétaro',['San Juan del Río','Corregidora','El Marqués']],
['EC','¿Cuál es la capital de Quintana Roo?','Chetumal',['Cancún','Playa del Carmen','Cozumel']],
['EC','¿Cuál es la capital de San Luis Potosí?','San Luis Potosí',['Ciudad Valles','Matehuala','Tamazunchale']],
['EC','¿Cuál es la capital de Sinaloa?','Culiacán',['Mazatlán','Los Mochis','Guasave']],
['EC','¿Cuál es la capital de Sonora?','Hermosillo',['Ciudad Obregón','Nogales','Guaymas']],
['EC','¿Cuál es la capital de Tabasco?','Villahermosa',['Cárdenas','Comalcalco','Macuspana']],
['EC','¿Cuál es la capital de Tamaulipas?','Ciudad Victoria',['Matamoros','Reynosa','Nuevo Laredo']],
['EC','¿Cuál es la capital de Tlaxcala?','Tlaxcala de Xicohténcatl',['Apizaco','Huamantla','Chiautempan']],
['EC','¿Cuál es la capital de Veracruz?','Xalapa-Enríquez',['Veracruz','Coatzacoalcos','Córdoba']],
['EC','¿Cuál es la capital de Yucatán?','Mérida',['Valladolid','Progreso','Izamal']],
['EC','¿Cuál es la capital de Zacatecas?','Zacatecas',['Fresnillo','Guadalupe','Jerez de García Salinas']],
['EC','¿Cuál es la capital de la Ciudad de México?','Ciudad de México',['Iztapalapa','Tlalpan','Coyoacán']],
['EC','¿Cuántos estados tiene México?','32 estados',['30 estados','31 estados','33 estados']],
['EC','¿Cuál estado tiene como capital a Guadalajara?','Jalisco',['Nayarit','Colima','Michoacán']],
['EC','¿Cuál estado tiene como capital a Monterrey?','Nuevo León',['Coahuila','Tamaulipas','San Luis Potosí']],
['EC','¿Cuál estado tiene como capital a Mérida?','Yucatán',['Campeche','Quintana Roo','Tabasco']],
['EC','¿Cuál estado tiene como capital a Morelia?','Michoacán',['Guerrero','Colima','Jalisco']],
['EC','¿Cuál estado tiene como capital a Oaxaca de Juárez?','Oaxaca',['Guerrero','Chiapas','Veracruz']],
['EC','¿Cuál estado tiene como capital a Xalapa?','Veracruz',['Tabasco','Oaxaca','Campeche']],
['EC','¿Cuál estado tiene como capital a Chilpancingo?','Guerrero',['Oaxaca','Michoacán','Morelos']],
['EC','¿En qué estado está Cancún?','Quintana Roo',['Yucatán','Campeche','Tabasco']],
['EC','¿En qué estado está Acapulco?','Guerrero',['Oaxaca','Michoacán','Colima']],
['EC','¿En qué estado está el puerto de Veracruz?','Veracruz',['Tabasco','Tamaulipas','Campeche']],

// ── DATOS GENERALES Y SÍMBOLOS ──────────────────────────────────
['GS','¿Cuál es el nombre oficial de México?','Estados Unidos Mexicanos',['República Federal Mexicana','Nación Mexicana Independiente','Gran México']],
['GS','¿Qué significa el nombre México?','El ombligo de la luna',['Tierra del águila','Ciudad de los dioses','El lago sagrado']],
['GS','¿Cuál es la extensión territorial de México?','1,964,375 km²',['1,500,000 km²','2,200,000 km²','1,750,000 km²']],
['GS','¿Con qué países limita México al sur?','Guatemala y Belice',['Honduras y Guatemala','El Salvador y Guatemala','Belice y Honduras']],
['GS','¿Con qué país limita México al norte?','Estados Unidos de América',['Canadá','Cuba','Belice']],
['GS','¿Cuál es la población de México según el censo 2020?','126 millones de habitantes',['100 millones','150 millones','90 millones']],
['GS','¿Cuáles son los símbolos patrios de México?','La bandera, el escudo y el himno nacional',['La bandera, el águila y el nopal','El escudo, el peso y el himno','La bandera, el peso y el aguila']],
['GS','¿En qué orden van los colores de la bandera mexicana?','Verde, blanco y rojo',['Rojo, blanco y verde','Blanco, verde y rojo','Verde, rojo y blanco']],
['GS','¿Qué representa el color verde de la bandera?','La esperanza',['La naturaleza','La unión','La independencia']],
['GS','¿Qué representa el color blanco de la bandera?','La pureza de los ideales',['La paz','La fe católica','La unidad nacional']],
['GS','¿Qué representa el color rojo de la bandera?','La sangre derramada por los héroes nacionales',['El valor','El fuego de la nación','La guerra de independencia']],
['GS','¿Quién escribió la letra del Himno Nacional Mexicano?','Francisco González Bocanegra',['Jaime Nunó','Agustín Lara','Vicente Riva Palacio']],
['GS','¿Quién compuso la música del Himno Nacional Mexicano?','Jaime Nunó',['Francisco González Bocanegra','Juventino Rosas','José Alfredo Jiménez']],
['GS','¿Cuándo se estrenó por primera vez el Himno Nacional?','15 de septiembre de 1854',['16 de septiembre de 1810','5 de mayo de 1862','27 de septiembre de 1821']],
['GS','¿Cuándo fue declarado oficial el Himno Nacional?','20 de octubre de 1943',['5 de febrero de 1917','16 de septiembre de 1910','15 de septiembre de 1850']],
['GS','¿Quién era presidente cuando se declaró oficial el Himno?','Manuel Ávila Camacho',['Lázaro Cárdenas','Miguel Alemán','Adolfo Ruiz Cortines']],
['GS','¿Cuál es el árbol nacional de México?','El ahuehuete',['El nopal','La ceiba','El cedro rojo']],
['GS','¿Cuál es el animal nacional de México?','El águila real',['El quetzal','El jaguar','El axolote']],
['GS','¿Cuál es la flor nacional de México?','La dalia',['La orquídea','La flor de nochebuena','El girasol']],
['GS','¿Cuándo cambió el nombre de Distrito Federal a Ciudad de México?','29 de enero de 2016',['1 de diciembre de 2012','16 de septiembre de 2015','5 de febrero de 2017']],
['GS','¿Qué presidente realizó el cambio del DF a CDMX?','Enrique Peña Nieto',['Andrés Manuel López Obrador','Felipe Calderón Hinojosa','Vicente Fox Quesada']],
['GS','¿Cuántas lenguas indígenas se hablan en México?','68 lenguas indígenas',['32 lenguas','120 lenguas','45 lenguas']],
['GS','¿Cuál es el idioma oficial de México?','El español',['El náhuatl','El español y el inglés','No tiene idioma oficial']],
['GS','¿Qué tan grande es la superficie total de México incluyendo islas y mar?','5,114,295 km²',['1,964,375 km²','2,500,000 km²','3,000,000 km²']],
['GS','¿Qué representa el escudo nacional de México?','Un águila posada en un nopal devorando una serpiente',['Un jaguar con una serpiente','Un águila con las alas extendidas','Un nopal con frutos rojos']],
['GS','¿Cuál es la leyenda del escudo nacional?','Los mexicas buscaban el lugar donde un águila comiera una serpiente sobre un nopal',['Una profecía azteca del fin del mundo','La batalla entre el águila y el quetzal','El origen del maíz sagrado']],

// ── ÉPOCA PREHISPÁNICA ──────────────────────────────────────────
['PH','¿Cuál cultura mesoamericana es llamada "la cultura madre"?','La olmeca',['La maya','La azteca','La tolteca']],
['PH','¿En qué período se desarrolló la cultura olmeca?','Período Preclásico',['Período Clásico','Período Posclásico','Período Colonial']],
['PH','¿Dónde estaba el centro ceremonial más importante de los olmecas?','La Venta, Tabasco',['Monte Albán, Oaxaca','Palenque, Chiapas','Teotihuacán, Estado de México']],
['PH','¿Por qué son conocidos los mayas en la ciencia?','Por ser astrónomos y matemáticos',['Por ser los mejores guerreros','Por construir las pirámides más altas','Por dominar la escritura alfabética']],
['PH','¿Quiénes inventaron el concepto del cero en Mesoamérica?','Los mayas',['Los aztecas','Los olmecas','Los toltecas']],
['PH','¿Cuál es la pirámide más alta de México?','Toniná, en Chiapas (75 metros)',['La Pirámide del Sol en Teotihuacán','El Castillo en Chichén Itzá','La Gran Pirámide de Cholula']],
['PH','¿Qué representa Kukulkán en Chichén Itzá?','La serpiente emplumada',['El dios del sol','El señor del inframundo','El dios de la lluvia']],
['PH','¿Cómo también se llama la pirámide de Kukulkán?','El Castillo',['El Templo Mayor','La Ciudadela','La Pirámide del Serpiente']],
['PH','¿Dónde se encuentran las Pirámides del Sol y de la Luna?','Teotihuacán, Estado de México',['Chichén Itzá, Yucatán','Palenque, Chiapas','Monte Albán, Oaxaca']],
['PH','¿Qué significa el nombre Teotihuacán?','Ciudad de los dioses',['Ciudad del sol','Lugar de los muertos','Monte sagrado de agua']],
['PH','¿Qué era la Calzada de los Muertos en Teotihuacán?','La avenida principal de 2 km de largo',['El camino a los sacrificios','El mercado central','El paso entre las dos pirámides']],
['PH','¿Cuál era el dios supremo de Teotihuacán?','Quetzalcóatl, la serpiente emplumada',['Tláloc','Huitzilopochtli','Tonatiuh']],
['PH','¿Dónde se desarrolló la civilización zapoteca?','En los valles de Etla, Tlacolula y Zimatlán en Oaxaca',['En el Valle de México','En la Península de Yucatán','En la Sierra Madre Occidental']],
['PH','¿Cuál fue la capital de los zapotecas?','Monte Albán',['Mitla','Cuilapan','El Tajín']],
['PH','¿Dónde se asentaron definitivamente los mexicas?','En Tenochtitlán, donde hoy es Ciudad de México',['En Tula, Hidalgo','En Teotihuacán','En Cholula, Puebla']],
['PH','¿Qué es el Aztlán?','El lugar mítico de origen de los mexicas',['La capital azteca','El templo principal azteca','El nombre original de Tenochtitlán']],
['PH','¿Qué son las chinampas?','Jardines flotantes sobre lagunas del Valle de México, hoy en Xochimilco',['Pirámides aztecas','Mercados flotantes','Templos sobre el agua']],
['PH','¿Cuáles eran las dos principales escuelas prehispánicas?','El Calmécac (nobles) y el Telpochcalli (pueblo)',['El Huey Calmécac y el Cuicacalli','El Templo Mayor y la Ciudadela','El Telpochcalli y el Coatepec']],
['PH','¿En qué año fue fundada Tenochtitlán?','En 1325',['En 1200','En 1428','En 1519']],
['PH','¿Cómo se llamaba el gobernante supremo de los mexicas?','Tlatoani',['Cihuacoatl','Huey Tlatoani','Tlacaelel']],
['PH','¿Quiénes formaron la Triple Alianza en 1427?','Tenochtitlán, Texcoco y Tlacopan',['Teotihuacán, Tula y Cholula','Aztlán, Texcoco y Tlaxcala','Tenochtitlán, Tlaxcala y Cholula']],
['PH','¿Quién era Huitzilopochtli para los aztecas?','El dios de la guerra y el sol',['El dios de la lluvia','El dios del viento','El dios del maíz']],
['PH','¿Quién era Tláloc para los aztecas?','La deidad de la lluvia y el rayo',['La deidad del viento','La deidad del fuego','La deidad de la muerte']],
['PH','¿Quién era Quetzalcóatl?','La serpiente emplumada, deidad suprema',['El dios de la muerte','El espíritu del maíz','El señor del inframundo']],
['PH','¿Quién era Coatlicue?','La diosa de la fertilidad y la tierra',['La diosa de la luna','La diosa del agua','La diosa de la guerra']],
['PH','¿Qué es un axolote?','Un anfibio sagrado asociado al dios Xólotl',['Una serpiente sagrada azteca','Una flor medicinal','Un tipo de maíz sagrado']],
['PH','¿Qué edificio era el corazón de Tenochtitlán?','El Templo Mayor',['La Pirámide de la Luna','El Castillo','La Ciudadela']],
['PH','¿Dónde se asentaron los toltecas?','Tula de Allende, Hidalgo',['Texcoco, Estado de México','Cholula, Puebla','Xochicalco, Morelos']],
['PH','¿Cuál tribu indígena es originaria de Michoacán?','Los purépechas (tarascos)',['Los zapotecas','Los mixtecos','Los huicholes']],
['PH','¿Cuántas zonas arqueológicas administra el INAH abiertas al público?','193 zonas arqueológicas',['50 zonas','500 zonas','32 zonas']],
['PH','¿En qué estado está la zona arqueológica de Monte Albán?','Oaxaca',['Guerrero','Chiapas','Puebla']],
['PH','¿En qué estado está la zona arqueológica de El Tajín?','Veracruz',['Tabasco','Yucatán','Tamaulipas']],
['PH','¿En qué estado están las ruinas de Palenque?','Chiapas',['Oaxaca','Campeche','Tabasco']],
['PH','¿En qué estado está la zona arqueológica de Cholula?','Puebla',['Tlaxcala','Morelos','Estado de México']],
['PH','¿Qué es un códice prehispánico?','Manuscrito en papel de corteza con temas históricos y religiosos',['Un tipo de pirámide escalonada','Un jeroglífico olmeca','Un calendario de piedra']],
['PH','¿Qué significaba el Tzompantli?','Altar con cráneos y estacas construido por varias culturas prehispánicas',['Una pirámide del sol','Un mercado azteca','Un juego de pelota']],
['PH','¿Cuál fue el producto más importante de comercio prehispánico?','El cacao',['El maíz','El oro','El jade']],
['PH','¿Cuál fue el alimento básico de los pueblos mesoamericanos?','El maíz',['El frijol','La calabaza','El chile']],
['PH','¿Qué es el "Hombre de Tepexpan"?','Un esqueleto precolombino de ~9,000 años hallado en 1947 cerca del Lago Texcoco',['El primer gobernante azteca','Un guerrero olmeca famoso','Un sacerdote maya descubierto en Palenque']],
['PH','¿Qué sistema de calendario usaban los mayas?','El sistema de Cuenta Larga',['El calendario solar de 365 días únicamente','El calendario lunar','El sistema decimal']],
['PH','¿Dónde se encuentra Calakmul?','Campeche',['Yucatán','Chiapas','Quintana Roo']],
['PH','¿Dónde se encuentra Xochicalco?','Morelos',['Estado de México','Guerrero','Puebla']],
['PH','¿Cuál civilización habitaba Tula?','Los toltecas',['Los aztecas','Los olmecas','Los mayas']],
['PH','¿Qué período cultural fue el de mayor desarrollo en Mesoamérica?','El Posclásico (950-1521 d.C.)',['El Preclásico','El Clásico','El Arcaico']],
['PH','¿Qué tribu era famosa por su orfebrería en oro y plata en Michoacán?','Los tarascos (purépechas)',['Los zapotecas','Los toltecas','Los totonacas']],
['PH','¿Cuál grupo indígena habita en las montañas de Chihuahua?','Los tarahumaras',['Los yaquis','Los huicholes','Los seris']],
['PH','¿Qué son los "Voladores de Papantla"?','Una danza ritual indígena de Veracruz asociada a la fertilidad',['Una fiesta olmeca','Un ritual maya de sacrificio','Una ceremonia purépecha']],
['PH','¿Qué cultura indígena del estado de Guanajuato es conocida?','Los chichimecas jonaz',['Los purépechas','Los otomíes','Los nahuas']],
['PH','¿En qué estado se localiza el sitio arqueológico de Cacaxtla?','Tlaxcala',['Puebla','Hidalgo','Estado de México']],

// ── CONQUISTA Y COLONIA ──────────────────────────────────────────
['CC','¿Quién conquistó el Imperio mexica?','Hernán Cortés',['Francisco Pizarro','Pánfilo de Narváez','Pedro de Alvarado']],
['CC','¿Quién fue la intérprete de Hernán Cortés?','La Malinche (también llamada Malinali, Malintzin o doña Marina)',['Sor Juana Inés de la Cruz','Josefa Ortiz de Domínguez','Catalina Xuárez']],
['CC','¿Quién fundó la Villa Rica de la Vera Cruz en 1519?','Hernán Cortés',['Diego Velázquez de Cuéllar','Francisco de Garay','Juan de Grijalva']],
['CC','¿Cuándo entraron los conquistadores a Tenochtitlán por primera vez?','8 de noviembre de 1519',['13 de agosto de 1521','25 de junio de 1520','12 de octubre de 1492']],
['CC','¿Quién era el emperador mexica cuando llegaron los españoles?','Moctezuma Xocoyotzin (Moctezuma II)',['Cuauhtémoc','Cuitláhuac','Ahuízotl']],
['CC','¿Qué evento histórico fue la Noche Triste?','La victoria azteca sobre los españoles el 30 de junio de 1520',['La caída de Tenochtitlán','La llegada de Cortés a México','El primer encuentro entre Cortés y Moctezuma']],
['CC','¿Cuándo cayó definitivamente Tenochtitlán ante los españoles?','13 de agosto de 1521',['30 de junio de 1520','8 de noviembre de 1519','25 de septiembre de 1522']],
['CC','¿Quién fue el último emperador mexica?','Cuauhtémoc',['Moctezuma II','Cuitláhuac','Axayácatl']],
['CC','¿Qué significa el nombre Cuauhtémoc?','El águila que desciende',['El guerrero del sol','El señor del agua','El viento emplumado']],
['CC','¿Por qué fue torturado Cuauhtémoc?','Para revelar la ubicación del tesoro de Moctezuma',['Por traicionar a su pueblo','Por aliarse con los españoles','Para firmar la rendición']],
['CC','¿Cómo se llamaba México durante la época colonial?','Nueva España',['Virreinato del Perú','Indias Occidentales','Nueva Castilla']],
['CC','¿Cuál era la máxima autoridad en Nueva España?','El virrey',['El arzobispo','El capitán general','El rey de España directamente']],
['CC','¿Quién fue el primer virrey de Nueva España?','Antonio de Mendoza y Pacheco',['Luis de Velasco','Hernán Cortés','Diego Colón']],
['CC','¿Cuándo fue creado el Virreinato de Nueva España?','8 de marzo de 1535',['12 de octubre de 1492','13 de agosto de 1521','2 de enero de 1540']],
['CC','¿Quiénes eran los "criollos" en la colonia?','Hijos de españoles nacidos en Nueva España',['Mestizos con educación española','Indígenas bautizados','Españoles venidos directamente de España']],
['CC','¿Qué era un "mestizo" en la Nueva España?','Hijo de español e indígena',['Hijo de español y africano','Hijo de dos criollos','Hijo de indígena y africano']],
['CC','¿Quiénes ocupaban el nivel más bajo en la jerarquía colonial?','Los esclavos africanos y asiáticos',['Los indígenas','Los mestizos','Los criollos pobres']],
['CC','¿Cuándo se estableció la primera imprenta en México?','En 1539, bajo el virrey Antonio de Mendoza',['En 1600','En 1722','En 1810']],
['CC','¿Cuál fue el primer periódico de México?','La Gaceta de México (1 de enero de 1722)',['El Despertador Americano','El Pensador Mexicano','La Gaceta del Gobierno']],
['CC','¿Qué mineral fue el más extraído durante la colonia?','La plata',['El oro','El cobre','El hierro']],
['CC','¿Cuándo apareció la Virgen de Guadalupe a Juan Diego?','En 1531, en el cerro del Tepeyac',['En 1521','En 1492','En 1600']],
['CC','¿Qué leyes del siglo XVI protegían a los indígenas?','Las Nuevas Leyes del 20 de noviembre de 1542',['Las Leyes de Burgos de 1512','El Código de Indias de 1680','El Reglamento de Encomiendas']],
['CC','¿Qué fue la encomienda colonial?','Institución que otorgaba a los conquistadores tierras e indígenas para trabajar',['Un impuesto colonial','Un tipo de hacienda','El sueldo de los virreyes']],
['CC','¿Qué fue la primera institución de educación superior para indígenas nobles?','El Colegio de Santa Cruz de Santiago Tlatelolco',['La Real y Pontificia Universidad','El Colegio de San Ildefonso','La Escuela de Artes y Oficios']],
['CC','¿Cuándo fue fundada la Real y Pontificia Universidad de México?','21 de septiembre de 1551',['1539','1650','1810']],
['CC','¿Qué fue el Tribunal de la Inquisición en México?','Institución religiosa que juzgaba herejías y desviaciones de la fe',['Un tribunal civil colonial','El máximo tribunal criminal','El consejo de virreyes']],
['CC','¿Qué eran los obrajes coloniales?','Centros artesanales que producían textiles y explotaban trabajadores indígenas y penados',['Haciendas de caña de azúcar','Minas de plata','Talleres de orfebrería']],
['CC','¿Cómo se llamaba el último virrey de Nueva España?','Juan Ruiz de Apodaca',['Félix María Calleja','Agustín de Iturbide','Antonio de Mendoza']],
['CC','¿Cuándo se estableció el primer cabildo del continente americano?','10 de julio de 1519 en Villa Rica de la Vera Cruz',['8 de noviembre de 1519','13 de agosto de 1521','8 de marzo de 1535']],
['CC','¿Qué alianza fue clave para que Cortés conquistara a los mexicas?','La alianza con los tlaxcaltecas',['La alianza con los mayas','La alianza con los zapotecas','La alianza con los purépechas']],

// ── INDEPENDENCIA ──────────────────────────────────────────────
['IN','¿Quién es conocido como el "Padre de la Patria" de México?','Miguel Hidalgo y Costilla',['José María Morelos y Pavón','Agustín de Iturbide','Vicente Guerrero']],
['IN','¿Qué imagen portaba Hidalgo en su estandarte?','La imagen de la Virgen de Guadalupe',['Un águila devorando una serpiente','La bandera de España','Un escudo indígena']],
['IN','¿Cuándo fue el Grito de Dolores que inició la Independencia?','16 de septiembre de 1810',['16 de septiembre de 1821','5 de mayo de 1862','27 de septiembre de 1821']],
['IN','¿En qué ciudad dio el Grito de Independencia el cura Hidalgo?','Dolores Hidalgo, Guanajuato',['Querétaro','Morelia, Michoacán','San Luis Potosí']],
['IN','¿Quién fue "La Corregidora"?','Josefa Ortiz de Domínguez',['Leona Vicario','Sor Juana Inés de la Cruz','La Malinche']],
['IN','¿Qué papel jugó Josefa Ortiz de Domínguez en la Independencia?','Avisó a los conspiradores cuando fueron descubiertos, precipitando el Grito',['Fue la esposa de Hidalgo','Financió el ejército insurgente','Escribió el plan de independencia']],
['IN','¿Quién fue Leona Vicario en la Independencia?','Heroína que informaba a los insurgentes sobre los movimientos del ejército realista',['La esposa de Morelos','La hermana de Hidalgo','La escritora del himno insurgente']],
['IN','¿Quién escribió los "Sentimientos de la Nación" en 1813?','José María Morelos y Pavón',['Miguel Hidalgo','Agustín de Iturbide','Vicente Guerrero']],
['IN','¿Qué proclamaba el documento "Sentimientos de la Nación"?','La independencia de América de España y la abolición de la esclavitud',['La formación de una monarquía mexicana','La creación del Ejército Trigarante','La rendición de los realistas']],
['IN','¿Qué fue la Conspiración de Querétaro?','Plan secreto para independizarse de España, descubierto en 1810',['La batalla que inició la guerra','El plan para asesinar al virrey','La firma del tratado de paz']],
['IN','¿Cuándo y dónde murió el padre Hidalgo?','30 de julio de 1811, en Chihuahua (fusilado)',['22 de diciembre de 1815, en Ecatepec','10 de abril de 1919, en Morelos','16 de septiembre de 1810, en Dolores']],
['IN','¿Cuándo y dónde fue ejecutado José María Morelos?','22 de diciembre de 1815, en San Cristóbal Ecatepec, Estado de México',['30 de julio de 1811, en Chihuahua','14 de febrero de 1831, en Oaxaca','13 de agosto de 1821, en Ciudad de México']],
['IN','¿Qué fue la Constitución de Cádiz de 1812?','La Constitución española que dividió Nueva España en 6 provincias',['La primera constitución mexicana independiente','El documento de independencia de México','El plan político de Morelos']],
['IN','¿Por qué se llama "Plaza de la Constitución" al Zócalo de CDMX?','En honor a la Constitución de Cádiz de 1812',['Por la Constitución de 1917','Por la Constitución de 1857','Por la Constitución de 1824']],
['IN','¿Cuál fue el primer periódico insurgente en México?','El Despertador Americano, fundado en 1810',['La Gaceta de México','El Pensador Mexicano','El Monitor Republicano']],
['IN','¿Qué fue el Plan de Iguala?','Documento del 24 de febrero de 1821 que proclamaba la independencia de Nueva España',['El plan de Morelos para liberar México','La conspiración de Querétaro','El manifiesto de Juárez contra la reelección']],
['IN','¿Quiénes firmaron el Plan de Iguala?','Agustín de Iturbide y Vicente Guerrero',['Hidalgo y Allende','Morelos y Guerrero','Iturbide y Allende']],
['IN','¿Cuáles fueron los tres principios del Plan de Iguala?','Religión, Independencia y Unión',['Libertad, Igualdad y Fraternidad','Federalismo, Independencia y Reforma','Unión, Progreso y Orden']],
['IN','¿Cuándo entró el Ejército Trigarante a la Ciudad de México?','27 de septiembre de 1821',['16 de septiembre de 1810','24 de febrero de 1821','5 de febrero de 1917']],
['IN','¿Qué fue el Tratado de Córdoba (1821)?','Acuerdo entre Iturbide y O\'Donojú que reconoció la independencia de México',['El tratado que cedió Texas a EUA','El pacto entre Juárez y Francia','La rendición de los insurgentes']],
['IN','¿Quién fue el primer presidente constitucional de México?','Guadalupe Victoria (1824-1829)',['Agustín de Iturbide','Antonio López de Santa Anna','Vicente Guerrero']],
['IN','¿Cuál fue la primera constitución del México independiente?','La Constitución Federal de 1824',['La Constitución de Apatzingán de 1814','La Constitución de Cádiz de 1812','La Constitución de 1857']],
['IN','¿Qué hizo Agustín de Iturbide en 1822?','Se coronó como Agustín I, Emperador de México',['Se convirtió en el primer presidente','Firmó el tratado de paz con España','Declaró la guerra a Estados Unidos']],
['IN','¿Qué fue el Plan de Casa Mata (1823)?','El plan de Santa Anna para deponer a Iturbide como emperador',['El plan para crear la primera constitución','El programa político de Guerrero','El manifiesto de los insurgentes']],
['IN','¿Cuántos intentos tuvo Santa Anna para llegar al poder?','Fue presidente 11 veces entre 1833 y 1855',['7 veces','5 veces','3 veces']],
['IN','¿Cuándo fue la Batalla de Chapultepec?','13 de septiembre de 1847',['5 de mayo de 1862','16 de septiembre de 1821','19 de septiembre de 1985']],
['IN','¿Quiénes defendieron el Castillo de Chapultepec en 1847?','Los Niños Héroes',['El Ejército Trigarante','El Batallón de San Patricio','Los lanceros de Oaxaca']],
['IN','¿Cuáles son los nombres de los seis Niños Héroes?','Juan Escutia, Juan de la Barrera, Agustín Melgar, Fernando Montes de Oca, Vicente Suárez y Francisco Márquez',['Pedro Infante, Jorge Negrete, Mario Moreno, Cantinflas, El Santo y Pedro Armendáriz','Hidalgo, Morelos, Guerrero, Allende, Aldama y Matamoros','Juárez, Díaz, Madero, Villa, Zapata y Carranza']],
['IN','¿Cuál de los Niños Héroes se envolvió en la bandera antes de morir?','Juan Escutia',['Francisco Márquez','Juan de la Barrera','Vicente Suárez']],
['IN','¿Cuál era el más joven de los Niños Héroes?','Francisco Márquez, con 12 años',['Juan Escutia','Vicente Suárez','Agustín Melgar']],
['IN','¿Qué cedió México a Estados Unidos con el Tratado de Guadalupe Hidalgo?','Más de la mitad del territorio mexicano (California, Arizona, Nuevo México, Texas, Nevada, Utah y otros)',['Solo el estado de Texas','Solo los territorios del norte','California y Texas únicamente']],
['IN','¿Cuándo se firmó el Tratado de Guadalupe Hidalgo?','2 de febrero de 1848',['2 de septiembre de 1836','24 de febrero de 1821','5 de mayo de 1862']],
['IN','¿Qué fue la Guerra de Reforma (1857-1860)?','Conflicto entre liberales (Juárez) y conservadores; ganaron los liberales',['La guerra contra la intervención francesa','La guerra México-Americana','La guerra de independencia de Texas']],
['IN','¿Quién fue Benito Juárez?','Presidente indígena zapoteca que promovió las Leyes de Reforma y separó la Iglesia del Estado',['El primer presidente de México','El padre del petróleo mexicano','El héroe de la independencia']],
['IN','¿Cuál es la frase más célebre de Benito Juárez?','Entre los individuos, como entre las naciones, el respeto al derecho ajeno es la paz',['La patria es primero','Tierra y libertad','Sufragio efectivo, no reelección']],
['IN','¿Cómo se conoce a Benito Juárez en la historia?','El Benemérito de las Américas',['El Padre de la Nación','El Apóstol de la Democracia','El Centauro del Norte']],
['IN','¿Cuándo nació Benito Juárez?','21 de marzo de 1806 en San Pablo Guelatao, Oaxaca',['5 de febrero de 1806 en Ciudad de México','16 de septiembre de 1810 en Dolores, Guanajuato','21 de marzo de 1830 en Oaxaca']],
['IN','¿De qué etnia era Benito Juárez?','Zapoteca',['Nahua','Maya','Mixteca']],
['IN','¿Quién dirigió la Batalla de Puebla del 5 de mayo de 1862?','Ignacio Zaragoza',['Benito Juárez','Porfirio Díaz','Leandro Valle']],
['IN','¿Por qué Francia intervino militarmente en México en 1862?','Porque Benito Juárez suspendió el pago de la deuda externa',['Para apoyar la independencia de México','Por disputa territorial','Para proteger a sus ciudadanos en México']],
['IN','¿Quién fue el Emperador del Segundo Imperio Mexicano?','Maximiliano de Habsburgo',['Agustín de Iturbide','Napoleón III','Fernando Maximiliano']],
['IN','¿Quién diseñó el Paseo de la Reforma en 1864?','Maximiliano de Habsburgo',['Porfirio Díaz','Benito Juárez','Sebastián Lerdo de Tejada']],
['IN','¿Cuándo y dónde murió Maximiliano de Habsburgo?','19 de junio de 1867 en el Cerro de las Campanas, Querétaro',['5 de mayo de 1862 en Puebla','27 de septiembre de 1821 en Ciudad de México','13 de agosto de 1521 en Tenochtitlán']],
['IN','¿Qué presidente renombró el Paseo de la Reforma?','Sebastián Lerdo de Tejada (1872-1876)',['Benito Juárez','Porfirio Díaz','Agustín de Iturbide']],
['IN','¿Cuáles son los dos emperadores que tuvo México?','Agustín de Iturbide y Maximiliano de Habsburgo',['Solo Agustín de Iturbide','Maximiliano y Napoleón III','Iturbide y Santa Anna']],
['IN','¿Qué fue el Plan de Ayutla (1854)?','El plan que terminó con la dictadura de Santa Anna',['El plan que inició la Revolución Mexicana','El manifiesto contra la Intervención Francesa','El programa de gobierno de Juárez']],

// ── REVOLUCIÓN ──────────────────────────────────────────────────
['RE','¿Cuándo inició oficialmente la Revolución Mexicana?','20 de noviembre de 1910',['16 de septiembre de 1810','5 de febrero de 1917','1 de enero de 1994']],
['RE','¿Qué fue el Porfiriato?','El período de gobierno de Porfirio Díaz (1876-1910), de 34 años',['El período de gobierno de Juárez','El gobierno de Santa Anna','El período colonial']],
['RE','¿Cuántos años gobernó Porfirio Díaz?','34 años',['20 años','15 años','50 años']],
['RE','¿Cuál fue el lema político de Francisco I. Madero?','Sufragio efectivo, no reelección',['Tierra y libertad','La patria es primero','Reforma, Libertad, Justicia y Ley']],
['RE','¿Qué fue el Plan de San Luis Potosí (1910)?','El llamado de Madero al levantamiento armado para evitar la reelección de Díaz',['El plan para repartir tierras entre campesinos','El plan de Carranza para derrocar a Huerta','El programa de gobierno de Zapata']],
['RE','¿Qué fue la Decena Trágica?','Golpe militar del 9 al 19 de febrero de 1913 que derrocó a Madero',['La masacre de estudiantes en 1968','La huelga de Cananea en 1906','La represión zapatista de 1919']],
['RE','¿Quién traicionó y derrocó a Francisco I. Madero?','Victoriano Huerta',['Pancho Villa','Emiliano Zapata','Venustiano Carranza']],
['RE','¿Cómo se conoce a Francisco I. Madero en la historia?','El Apóstol de la Democracia',['El Centauro del Norte','El Padre de la Revolución','El Caudillo del Sur']],
['RE','¿Qué fue el Plan de Ayala (1911)?','El plan de Zapata para devolver tierras a los campesinos, rechazando a Madero',['El plan de Madero para la democracia','El plan de Carranza para la constitución','El plan de Villa para el norte']],
['RE','¿Cuál era el lema del movimiento zapatista?','Tierra y libertad',['La patria es primero','Sufragio efectivo, no reelección','Reforma, Libertad, Justicia y Ley']],
['RE','¿Cuándo y dónde fue asesinado Emiliano Zapata?','10 de abril de 1919, en la hacienda de Chinameca, Morelos',['20 de julio de 1923, Parral, Chihuahua','22 de febrero de 1913, Ciudad de México','17 de julio de 1928, Ciudad de México']],
['RE','¿Con qué apodo se conocía a Emiliano Zapata?','El Caudillo del Sur',['El Centauro del Norte','El Apóstol de la Democracia','El Benemérito de las Américas']],
['RE','¿Cuál era el nombre real de Pancho Villa?','José Doroteo Arango Arámbula',['Francisco Villa Reyes','José Francisco Villa Morales','Francisco Doroteo Arámbula Reyes']],
['RE','¿Con qué apodo se conocía a Pancho Villa?','El Centauro del Norte',['El Caudillo del Sur','El Apóstol de la Democracia','El General del Pueblo']],
['RE','¿Cuándo y dónde fue asesinado Pancho Villa?','20 de julio de 1923 en Parral, Chihuahua',['10 de abril de 1919 en Morelos','17 de julio de 1928 en Ciudad de México','22 de febrero de 1913 en Ciudad de México']],
['RE','¿Qué fue el Plan de Guadalupe (1913)?','El plan de Carranza para desconocer el gobierno ilegal de Victoriano Huerta',['El plan para repartir tierras del norte','El programa político de Madero','El manifiesto zapatista contra Díaz']],
['RE','¿Cuándo y dónde fue promulgada la actual Constitución Política de México?','5 de febrero de 1917 en Querétaro',['5 de febrero de 1857 en Ciudad de México','24 de febrero de 1821 en Córdoba','1 de enero de 1924 en Querétaro']],
['RE','¿Qué hizo Lázaro Cárdenas el 18 de marzo de 1938?','Nationalizó la industria petrolera, expropiando las empresas extranjeras',['Fundó el Partido Revolucionario Institucional','Creó el IMSS','Firmó el Tratado de Libre Comercio']],
['RE','¿Qué fue la Guerra Cristera (1926-1929)?','Conflicto entre el gobierno federal y milicias católicas que resistían la Ley Calles',['La lucha estudiantil de 1968','La rebelión zapatista de 1994','La guerra contra la intervención francesa']],
['RE','¿Quién fundó el Banco de México en 1925?','Plutarco Elías Calles',['Lázaro Cárdenas','Álvaro Obregón','Manuel Ávila Camacho']],
['RE','¿Cuándo se otorgó el derecho al voto a las mujeres en México?','17 de octubre de 1953 (presidencia de Adolfo Ruiz Cortines)',['16 de septiembre de 1917','5 de febrero de 1857','1 de enero de 1946']],
['RE','¿Cuándo fue la masacre de estudiantes en Tlatelolco?','2 de octubre de 1968',['26 de julio de 1968','19 de septiembre de 1985','27 de septiembre de 2014']],
['RE','¿Quién era presidente durante la masacre de Tlatelolco?','Gustavo Díaz Ordaz',['Luis Echeverría Álvarez','José López Portillo','Miguel de la Madrid']],
['RE','¿Quién nationalizó la banca en México en 1982?','José López Portillo (1 de septiembre de 1982)',['Miguel de la Madrid','Lázaro Cárdenas','Carlos Salinas de Gortari']],
['RE','¿Cuándo entró en vigor el TLCAN (Tratado de Libre Comercio)?','1 de enero de 1994',['17 de diciembre de 1992','1 de enero de 1990','5 de febrero de 1993']],
['RE','¿Qué fue el EZLN (Ejército Zapatista de Liberación Nacional)?','Movimiento armado que surgió en Chiapas en 1994 contra el TLCAN y el neoliberalismo',['Un partido político de izquierda','El ejército federal mexicano','Un sindicato de trabajadores del campo']],
['RE','¿Qué fue el caso Ayotzinapa?','La desaparición forzada de 43 normalistas el 27 de septiembre de 2014 en Iguala, Guerrero',['La masacre de Tlatelolco de 1968','La represión de la huelga de Cananea','El golpe de La Decena Trágica']],
['RE','¿Quién fundó el Partido Nacional Revolucionario (antecedente del PRI) en 1929?','Plutarco Elías Calles',['Lázaro Cárdenas','Álvaro Obregón','Venustiano Carranza']],
['RE','¿Qué unidad militar mexicana participó en la Segunda Guerra Mundial?','El Escuadrón 201 (Fuerza Aérea Expedicionaria Mexicana)',['El Batallón de San Patricio','La División del Norte','El Ejército Trigarante']],
['RE','¿Qué presidente declaró la guerra a las potencias del Eje en 1942?','Manuel Ávila Camacho',['Lázaro Cárdenas','Adolfo Ruiz Cortines','Miguel Alemán']],
['RE','¿Qué fue la huelga de Cananea (1906)?','Una huelga de mineros en Sonora, precursora de la Revolución Mexicana',['La huelga de ferroviarios de 1959','El movimiento estudiantil de 1968','La huelga general de 1910']],
['RE','¿Cuál es el apodo de Porfirio Díaz?','El llorón de Icamole',['El caudillo de Oaxaca','El centauro del sur','El señor de la dictadura']],
['RE','¿Qué fue el Maximato (1928-1934)?','El período en que Plutarco Elías Calles controlaba el poder detrás de tres presidentes títere',['El gobierno de Maximiliano de Habsburgo','El período de Madero','La presidencia de Obregón']],
['RE','¿Qué fue La Adelita?','Un célebre corrido de la Revolución Mexicana',['Una heroína de la independencia','El lema de Zapata','Un baile típico de Jalisco']],
['RE','¿Quién fue Cananea para la historia de México?','La cuna de la Revolución Mexicana (por la huelga de 1906)',['El lugar del último combate revolucionario','La ciudad donde murió Madero','El sitio del primer grito de independencia']],

// ── GEOGRAFÍA Y TURISMO ──────────────────────────────────────────
['GT','¿Cuántas penínsulas tiene México?','Dos (Baja California y Yucatán)',['Tres','Una','Cuatro']],
['GT','¿Cuál es el río más largo de México?','El Río Bravo (también llamado Río Grande)',['El Río Usumacinta','El Río Lerma','El Río Colorado']],
['GT','¿Cuál es el lago más grande de México?','El Lago de Chapala, en Jalisco',['El Lago de Texcoco','El Lago de Pátzcuaro','La Laguna de Términos']],
['GT','¿Cuál es la montaña más alta de México?','Citlaltépetl (Pico de Orizaba), entre Veracruz y Puebla, con 5,610 metros',['Popocatépetl','Nevado de Toluca (Xinantécatl)','Iztaccíhuatl']],
['GT','¿Con qué apodos se conocen el Popocatépetl y el Iztaccíhuatl?','Don Goyo y la Mujer Dormida',['Los volcanes de Puebla','Los guardianes del Valle','Los titanes del sur']],
['GT','¿Qué significa Popocatépetl en náhuatl?','Montaña que humea',['Montaña sagrada','Ciudad de los dioses','Monte de la serpiente']],
['GT','¿Cuál es el cuerpo de agua entre la Península de Baja California y el continente?','El Mar de Cortés (Golfo de California)',['El Mar Caribe','El Océano Pacífico','El Golfo de México']],
['GT','¿En qué estado se ubica el Cañón del Sumidero?','Chiapas',['Guerrero','Oaxaca','Durango']],
['GT','¿En qué estados está el Santuario de la Mariposa Monarca?','Michoacán y Estado de México',['Guerrero y Oaxaca','Jalisco y Colima','Chiapas y Oaxaca']],
['GT','¿En qué estado está la Selva Lacandona?','Chiapas',['Tabasco','Campeche','Yucatán']],
['GT','¿Cómo se conoce al centro histórico de la Ciudad de México?','La Ciudad de los Palacios',['El Corazón de México','La Gran Tenochtitlán','El Centro Colonial']],
['GT','¿Qué edificio de 43 pisos de Ciudad de México resistió tres terremotos?','La Torre Latinoamericana',['El World Trade Center','La Torre Mayor','El Hotel Presidente']],
['GT','¿Cuándo se inauguró el Ángel de la Independencia?','16 de septiembre de 1910',['27 de septiembre de 1821','5 de mayo de 1862','20 de noviembre de 1910']],
['GT','¿Quién inauguró el Museo Nacional de Antropología?','Adolfo López Mateos (1964)',['Gustavo Díaz Ordaz','Luis Echeverría','José López Portillo']],
['GT','¿Cómo se llaman las coloridas embarcaciones de los canales de Xochimilco?','Trajineras',['Canoas','Chalupas','Balsas']],
['GT','¿Qué estado de México produce más calzado en el país?','Guanajuato',['Jalisco','Puebla','Nuevo León']],
['GT','¿Dónde se encuentran los famosos clavadistas de La Quebrada?','Acapulco, Guerrero',['Puerto Vallarta, Jalisco','Manzanillo, Colima','Mazatlán, Sinaloa']],
['GT','¿Qué son los "Pueblos Mágicos" en México?','Poblaciones reconocidas por su riqueza histórica y cultural, programa de la SECTUR',['Zonas arqueológicas declaradas patrimonio','Ciudades coloniales del siglo XVI','Reservas naturales de México']],
['GT','¿Por cuántas veces es considerada heroica la ciudad de Veracruz?','Cuatro veces heroica',['Dos veces','Tres veces','Cinco veces']],
['GT','¿Qué famoso callejón existe en Guanajuato?','El Callejón del Beso',['El Callejón de la Noche Triste','El Callejón de los Enamorados','El Callejón del Quijote']],
['GT','¿Cuál es el tercer monolito más grande del mundo que está en México?','La Peña de Bernal, en Querétaro',['El Templo Mayor','La Pirámide del Sol','El Cerro de la Silla']],
['GT','¿Cuál es la icónica montaña de Monterrey?','El Cerro de la Silla',['El Cerro del Obispado','La Sierra Madre','El Cerro de las Mitras']],
['GT','¿Cuántas Sierras Madres tiene México?','Dos: la Sierra Madre Oriental y la Sierra Madre Occidental',['Tres','Una','Cuatro']],
['GT','¿Cuál es el estado más grande de México?','Chihuahua',['Sonora','Coahuila','Durango']],
['GT','¿Cuál es el estado más pequeño de México?','Tlaxcala',['Colima','Aguascalientes','Morelos']],
['GT','¿Qué estados forman la frontera norte de México con Estados Unidos?','Baja California, Sonora, Chihuahua, Coahuila, Nuevo León y Tamaulipas',['Jalisco, Sinaloa, Durango, Coahuila, Nuevo León y Tamaulipas','Baja California, Sonora, Sinaloa, Chihuahua, Coahuila y Tamaulipas','Todos los estados del norte']],
['GT','¿Dónde se localizan las Grutas de Cacahuamilpa?','Guerrero',['Morelos','Puebla','Oaxaca']],
['GT','¿Qué reserva natural única está en el Golfo de México?','El Arrecife Veracruzano',['La Biósfera de Sian Ka\'an','El Arrecife Mesoamericano','La Reserva de la Mariposa Monarca']],
['GT','¿Cuál es la Estela de Luz y cuándo fue inaugurada?','Un monumento que celebra el Bicentenario de la Independencia, inaugurado el 7 de enero de 2012',['El Ángel de la Independencia, en 1910','El Monumento a la Revolución, en 1938','La Torre Latinoamericana, en 1956']],
['GT','¿Cuál es la avenida más importante de la Ciudad de México?','La Avenida Paseo de la Reforma',['La Avenida Insurgentes','La Calzada de Tlalpan','El Periférico']],
['GT','¿Qué ciudad colonial de México es famosa por su arquitectura y sus chiles en nogada?','Puebla',['Oaxaca','Guanajuato','San Cristóbal de las Casas']],

// ── CIVISMO Y GOBIERNO ──────────────────────────────────────────
['CG','¿Cuál es la forma de gobierno de México?','República representativa, democrática, laica y federal',['Monarquía constitucional','República presidencialista centralista','Federación parlamentaria']],
['CG','¿Cuáles son los tres Poderes de la Unión en México?','Ejecutivo, Legislativo y Judicial',['Federal, Estatal y Municipal','Presidente, Congreso y Ejército','Gobierno, Oposición y Sociedad Civil']],
['CG','¿Quién ejerce el Poder Ejecutivo en México?','El Presidente de la República',['El Senado','El Congreso de la Unión','El Gabinete presidencial']],
['CG','¿Cuánto dura el período presidencial en México?','Seis años sin posibilidad de reelección',['Cuatro años','Cinco años con una posible reelección','Seis años con una posible reelección']],
['CG','¿Cuándo se celebran las elecciones presidenciales en México?','El primer domingo de junio cada seis años',['El 16 de septiembre de cada seis años','El primer domingo de julio cada cuatro años','El 5 de mayo cada seis años']],
['CG','¿Qué institución protege los derechos del consumidor en México?','La PROFECO (Procuraduría Federal del Consumidor)',['El SAT','El IMSS','La Secretaría de Economía']],
['CG','¿Cuántos diputados integran la Cámara de Diputados?','500 diputados',['300 diputados','400 diputados','128 diputados']],
['CG','¿Cuántos senadores integran el Senado de la República?','128 senadores',['64 senadores','100 senadores','500 senadores']],
['CG','¿Cuántos artículos tiene la Constitución Política de México?','136 artículos',['120 artículos','200 artículos','97 artículos']],
['CG','¿Cuál es el nombre completo de la Constitución de México?','Constitución Política de los Estados Unidos Mexicanos',['Constitución Federal de México','Constitución Nacional Mexicana','Ley Fundamental de los Estados Unidos Mexicanos']],
['CG','¿Qué artículo de la Constitución trata los derechos humanos y prohíbe la esclavitud?','El Artículo 1',['El Artículo 2','El Artículo 3','El Artículo 27']],
['CG','¿Qué artículo de la Constitución establece que la educación es gratuita y obligatoria?','El Artículo 3',['El Artículo 1','El Artículo 5','El Artículo 31']],
['CG','¿Qué artículo de la Constitución regula a los extranjeros en México?','El Artículo 33',['El Artículo 27','El Artículo 35','El Artículo 40']],
['CG','¿Cuál es la edad mínima para votar en México?','18 años',['16 años','21 años','17 años']],
['CG','¿Qué institución organiza las elecciones en México?','El INE (Instituto Nacional Electoral)',['El IFE','El PRI','La Suprema Corte']],
['CG','¿Cuándo fue fundado el INE?','10 de febrero de 2014',['11 de octubre de 1990','16 de septiembre de 2000','5 de febrero de 2006']],
['CG','¿Quién aparece en el billete de 100 pesos?','Sor Juana Inés de la Cruz',['Benito Juárez','Miguel Hidalgo','Nezahualcóyotl']],
['CG','¿Quién aparece en el billete de 500 pesos?','Benito Juárez',['Sor Juana Inés de la Cruz','Francisco I. Madero','Diego Rivera']],
['CG','¿Quién aparece en el billete de 200 pesos?','Miguel Hidalgo y José María Morelos',['Benito Juárez y Porfirio Díaz','Zapata y Villa','Madero y Carranza']],
['CG','¿Quién aparece en el billete de 1,000 pesos?','Francisco I. Madero, Hermila Galindo y Carmen Serdán',['Benito Juárez y Josefa Ortiz','Diego Rivera y Frida Kahlo','Zapata, Villa y Carranza']],
['CG','¿Qué partido gobernó México durante más de 70 años?','El PRI (1930-2000)',['El PAN','El PRD','El MORENA']],
['CG','¿Cuándo fue creado el IMSS?','19 de enero de 1943 (presidencia de Manuel Ávila Camacho)',['1 de septiembre de 1935','5 de febrero de 1917','1 de enero de 1960']],
['CG','¿Cuál es la sede oficial del Poder Ejecutivo?','El Palacio Nacional en la Ciudad de México',['Los Pinos','La Secretaría de Gobernación','La Suprema Corte de Justicia']],
['CG','¿Cuántos magistrados integran la Suprema Corte de Justicia de la Nación?','11 magistrados',['9 magistrados','15 magistrados','7 magistrados']],
['CG','¿Qué artículo de la Constitución establece que México es una República federal?','El Artículo 40',['El Artículo 1','El Artículo 27','El Artículo 133']],
['CG','¿Qué artículo cubre el derecho de petición?','El Artículo 8',['El Artículo 6','El Artículo 10','El Artículo 14']],
['CG','¿Qué artículo trata sobre los derechos políticos de los ciudadanos?','El Artículo 35',['El Artículo 33','El Artículo 31','El Artículo 40']],
['CG','¿Cuándo se estableció el Registro Civil en México?','28 de julio de 1859',['16 de septiembre de 1810','5 de febrero de 1857','1 de enero de 1870']],
['CG','¿Cuándo se emitió la primera acta de nacimiento en México?','10 de noviembre de 1859',['28 de julio de 1859','1 de enero de 1870','5 de febrero de 1917']],
['CG','¿Qué secretaría recauda los impuestos en México?','La Secretaría de Hacienda y Crédito Público (SHCP), a través del SAT',['La Secretaría de Economía','La Secretaría de Gobernación','El Banco de México']],
['CG','¿Cuántos consulados tiene México en el mundo?','67 consulados',['50 consulados','80 consulados','32 consulados']],
['CG','¿Cuántos años dura el mandato de un senador en México?','6 años',['3 años','4 años','5 años']],
['CG','¿Cuántos años dura el mandato de un diputado federal en México?','3 años',['6 años','4 años','2 años']],
['CG','¿Cómo debe ser la educación según la Constitución Mexicana?','Laica, gratuita, obligatoria, pública, universal, inclusiva y de calidad',['Solo gratuita y laica','Obligatoria y religiosa','Solo pública y gratuita']],

// ── CIENCIA, EDUCACIÓN Y DEPORTES ──────────────────────────────
['CE','¿Quién fue el primer Secretario de Educación Pública de México?','José Vasconcelos (1921)',['Jaime Torres Bodet','Agustín Yáñez','Fernando Solana']],
['CE','¿Cuál es la universidad más antigua de México?','La UNAM (Universidad Nacional Autónoma de México)',['El IPN','La UAM','La Universidad de Guadalajara']],
['CE','¿Cuándo fue fundada la UNAM?','22 de septiembre de 1910 (Porfirio Díaz / Justo Sierra)',['1 de enero de 1936','1 de enero de 1974','15 de septiembre de 1867']],
['CE','¿Cuál es el lema de la UNAM?','"Por mi raza hablará el espíritu"',['Técnica al servicio de la Patria','En Calli Ixcahuicopa','La libertad y el saber']],
['CE','¿A quién se le atribuye el lema de la UNAM?','A José Vasconcelos',['A Justo Sierra','A Lázaro Cárdenas','A Porfirio Díaz']],
['CE','¿Qué institución técnica creó Lázaro Cárdenas?','El IPN (Instituto Politécnico Nacional)',['La UNAM','La UAM','El CONALEP']],
['CE','¿Cuándo fue creado el IPN?','1 de enero de 1936',['22 de septiembre de 1910','1 de enero de 1974','2 de diciembre de 1867']],
['CE','¿Cuál es el lema del IPN?','"Técnica al servicio de la Patria"',['Por mi raza hablará el espíritu','En Calli Ixcahuicopa','Educación para la vida']],
['CE','¿Quién inventó la televisión a color?','Guillermo González Camarena, en 1940',['Rodolfo Neri Vela','Luis Miramontes','Guillermo del Toro']],
['CE','¿Quién inventó la píldora anticonceptiva en México?','Luis Ernesto Miramontes Cárdenas, el 15 de octubre de 1951',['Guillermo González Camarena','Mario Molina','José María Molina']],
['CE','¿Qué mexicanos han ganado el Premio Nobel?','Alfonso García Robles (Paz, 1982), Octavio Paz (Literatura, 1990) y Mario Molina (Química, 1995)',['Solo Octavio Paz','Solo Mario Molina','Carlos Fuentes y Octavio Paz']],
['CE','¿Por qué investigación ganó Mario Molina el Nobel de Química?','Por su investigación sobre la capa de ozono',['Por descubrir la penicilina','Por su trabajo sobre energía nuclear','Por inventar el GPS']],
['CE','¿Quién fue el primer astronauta mexicano?','Rodolfo Neri Vela, el 26 de noviembre de 1985',['Katya Echazarreta','Guillermo González Camarena','Alfonso García Robles']],
['CE','¿Quién fue la primera mexicana en ir al espacio?','Katya Echazarreta, en junio de 2022 (Blue Origin)',['Soraya Jiménez','Ana Guevara','Lupita Jones']],
['CE','¿Cuándo y dónde se realizaron las Olimpiadas de México?','12 de octubre de 1968 en Ciudad de México',['1970','1986','1972']],
['CE','¿En qué años fue México sede del Mundial de Futbol?','1970 y 1986 (y 2026)',['1970 y 1994','1986 y 2002','1970 y 1982']],
['CE','¿Cuál fue el deporte declarado nacional de México en 1933?','La charrería (rodeo mexicano)',['El futbol','El béisbol','La lucha libre']],
['CE','¿Cómo se llama realmente el famoso luchador "El Santo"?','Rodolfo Guzmán Huerta',['Mario Moreno','Hugo Sánchez','Julio César Chávez']],
['CE','¿Con qué apodo se conoce a Javier Hernández?','"Chicharito"',['El Matador','El Tri','El Kaiser']],
['CE','¿Qué arquitecto mexicano ganó el Premio Pritzker en 1980?','Luis Barragán',['Mario Pani','Pedro Ramírez Vázquez','Ricardo Legorreta']],
['CE','¿Quién ganó la medalla de oro olímpica en halterofilia en los Juegos de Sydney 2000?','Soraya Jiménez Mendivil',['Ana Guevara','Lupita Jones','María del Rosario Espinoza']],
['CE','¿Cuándo fue inaugurada la primera línea del Metro de CDMX?','4 de septiembre de 1969 (Línea Rosa)',['1 de enero de 1970','16 de septiembre de 1968','5 de febrero de 1972']],
['CE','¿Quién fue la primera médica mujer en México?','Matilde Montoya, en 1887',['Sor Juana Inés de la Cruz','Hermila Galindo','Rosario Castellanos']],
['CE','¿Cuándo fue fundada la UAM (Universidad Autónoma Metropolitana)?','1 de enero de 1974 (gobierno de Luis Echeverría)',['22 de septiembre de 1910','1 de enero de 1936','2 de diciembre de 1867']],
['CE','¿Quién ganó las tres últimas coronas de Miss Universo para México?','Lupita Jones (1991), Ximena Navarrete (2010) y Andrea Meza (2020)',['Solo Lupita Jones','Lupita Jones y Ximena Navarrete únicamente','Ximena Navarrete y Andrea Meza únicamente']],
['CE','¿Cuándo se declaró obligatoria y gratuita la educación primaria en México?','2 de diciembre de 1867, por decreto de Benito Juárez',['5 de febrero de 1917','1 de enero de 1921','20 de noviembre de 1910']],
['CE','¿Cuál es el sistema que abastece de agua a CDMX y el Estado de México?','El Sistema Cutzamala',['El Sistema Lerma','El Acueducto del Virrey','El Proyecto Temascaltepec']],
['CE','¿Quién diseñó las Torres de Satélite en el Estado de México?','Luis Barragán (con Mathias Goeritz)',['Pedro Ramírez Vázquez','Mario Pani','Agustín Hernández']],
['CE','¿Qué boxeador mexicano es conocido como "El César del Boxeo"?','Julio César Chávez',['Canelo Álvarez','Rubén el Ratón Olivares','Salvador Sánchez']],
['CE','¿Cuál fue el récord de Ana Gabriela Guevara en los 400 metros en Atenas 2004?','Medalla de plata con 48.89 segundos',['Medalla de oro con 47.50 segundos','Medalla de bronce con 49.12 segundos','Medalla de plata con 47.93 segundos']],

// ── LITERATURA, ARTE Y CINE ──────────────────────────────────────
['LA','¿Por qué es famosa Sor Juana Inés de la Cruz?','Fue la escritora y poeta más importante del período virreinal en México',['Fue la primera presidenta de México','Fue la pintora fundadora del muralismo','Fue heroína de la independencia']],
['LA','¿Con qué apodos se conoce a Sor Juana Inés de la Cruz?','La Décima Musa y La Fénix de América',['La Corregidora y La Heroína','La Catrina y La Adelita','La Malinche y La Profetisa']],
['LA','¿Qué obras escribió Sor Juana Inés de la Cruz?','"Primero Sueño", "Redondillas", "Los empeños de una casa" y "Amor es más laberinto"',['"Cien años de soledad" y "El coronel"','"Pedro Páramo" y "El Llano en llamas"','"La región más transparente" y "La muerte de Artemio Cruz"']],
['LA','¿Quién representa el muralismo mexicano por excelencia?','Diego Rivera',['Frida Kahlo','Rufino Tamayo','José Clemente Orozco']],
['LA','¿Quién pintó los murales del Palacio Nacional en Ciudad de México?','Diego Rivera',['José Clemente Orozco','David Alfaro Siqueiros','Rufino Tamayo']],
['LA','¿Por qué es famosa Frida Kahlo?','Por ser la pintora latinoamericana más importante, conocida por sus autorretratos',['Por ser la primera mujer escritora de México','Por sus murales en edificios públicos','Por ser actriz de la época de oro del cine']],
['LA','¿Cuál es el nombre completo de Frida Kahlo?','Magdalena Carmen Frida Kahlo Calderón',['Frida Calderón Rivera','María Magdalena Kahlo','Frida María Kahlo Morales']],
['LA','¿Quién escribió "El Llano en llamas"?','Juan Rulfo',['Carlos Fuentes','Octavio Paz','José Emilio Pacheco']],
['LA','¿Quién escribió "La región más transparente" en 1958?','Carlos Fuentes',['Juan Rulfo','Octavio Paz','Jorge Ibargüengoitia']],
['LA','¿Quién escribió "La noche de Tlatelolco"?','Elena Poniatowska',['Rosario Castellanos','Carlos Fuentes','Juan Rulfo']],
['LA','¿Cuál es el teatro más prestigioso de México?','El Palacio de Bellas Artes',['El Teatro Juárez','El Teatro Nacional','El Auditorio Nacional']],
['LA','¿Cuándo fue inaugurado el Palacio de Bellas Artes?','29 de septiembre de 1934 (presidencia de Abelardo L. Rodríguez)',['16 de septiembre de 1910','5 de mayo de 1917','1 de enero de 1935']],
['LA','¿Cuál fue la primera película sonora mexicana?','"Santa" (1931)',['Así se quiere en Jalisco','El presidente paseando en Chapultepec','Macario']],
['LA','¿Cuándo inició la Época de Oro del cine mexicano?','En 1935',['En 1920','En 1945','En 1960']],
['LA','¿Cuál es el máximo premio del cine mexicano?','El Premio Ariel',['El Oscar','El Globo de Oro','El BAFTA']],
['LA','¿Qué mexicano ganó dos premios Oscar como mejor actor?','Anthony Quinn',['Cantinflas','Pedro Infante','Jorge Negrete']],
['LA','¿Qué directores mexicanos han ganado el Oscar a mejor director?','Alejandro González Iñárritu y Alfonso Cuarón',['Guillermo del Toro y Rodrigo Prieto','Guillermo del Toro y Alfonso Cuarón','Carlos Carrera y Arturo Ripstein']],
['LA','¿Quién ganó el Globo de Oro 2018 como mejor director?','Guillermo del Toro (por "La forma del agua")',['Alfonso Cuarón','Alejandro González Iñárritu','Carlos Reygadas']],
['LA','¿Quién interpretó a El Chavo del 8?','Roberto Gómez Bolaños (Chespirito)',['Cantinflas','Pedro Infante','Mario Moreno']],
['LA','¿Cuál es el nombre real de Cantinflas?','Mario Fortino Alfonso Moreno Reyes',['Roberto Gómez Bolaños','Mario Morales Reyes','Francisco Moreno']],
['LA','¿Qué pintó principalmente José María Velasco?','Paisajes naturales de México',['Retratos de revolucionarios','Murales históricos','Escenas prehispánicas']],
['LA','¿Quién pintó "La Dualidad" en el Museo de Antropología?','Rufino Tamayo',['Diego Rivera','Frida Kahlo','David Alfaro Siqueiros']],
['LA','¿Qué premio literario en lengua española ganaron Paz, Fuentes, Poniatowska y Pacheco?','El Premio Cervantes',['El Premio Nobel de Literatura','El Premio Ariel','El Premio Nacional de Literatura']],
['LA','¿Quién ganó el Premio Nobel de Literatura en 1990?','Octavio Paz',['Carlos Fuentes','Juan Rulfo','Elena Poniatowska']],
['LA','¿Quién fue el actor que representó al típico mexicano de clase trabajadora en el cine?','Cantinflas (Mario Moreno)',['Pedro Infante','Jorge Negrete','Anthony Quinn']],
['LA','¿Qué fue la Primera película mexicana de la historia (1896)?','"El presidente de la República paseando a caballo en el bosque de Chapultepec", con Porfirio Díaz',['Santa','Macario','Así se quiere en Jalisco']],
['LA','¿Quién fue el famoso dibujante que creó las calaveras artísticas mexicanas?','José Guadalupe Posada',['Diego Rivera','Frida Kahlo','David Alfaro Siqueiros']],
['LA','¿Qué obra de Rosario Castellanos describe la vida indígena en Chiapas?','"Balún Canán"',['La región más transparente','La noche de Tlatelolco','El llano en llamas']],
['LA','¿Quién escribió el libro "La Sucesión Presidencial" en 1910, criticando el régimen de Díaz?','Francisco I. Madero',['Porfirio Díaz','Venustiano Carranza','Ricardo Flores Magón']],
['LA','¿Qué cómic mexicano creó Gabriel Vargas?','"La familia Burrón"',['El Santo vs Dracula','Kalimán','Los Supermachos']],

// ── MÚSICA, FIESTAS Y COMIDA ──────────────────────────────────────
['MF','¿Cuál es la danza nacional de México?','El jarabe tapatío',['La cumbia','El danzón','El huapango']],
['MF','¿De qué estado es el jarabe tapatío?','Jalisco',['Veracruz','Michoacán','Oaxaca']],
['MF','¿Qué son los Voladores de Papantla?','Una danza ritual indígena de Veracruz que simboliza la fertilidad y el inicio del año',['Un baile típico de Oaxaca','Un ritual maya de sacrificio','Una ceremonia purépecha de Michoacán']],
['MF','¿De dónde es el son jarocho?','Veracruz',['Jalisco','Oaxaca','Yucatán']],
['MF','¿Qué canción popular es el himno de Veracruz?','"La Bamba"',['El Jarabe Tapatío','La Sandanga','El Huapango']],
['MF','¿De dónde es el mariachi?','Jalisco',['Sinaloa','Sonora','Guanajuato']],
['MF','¿Qué es la Guelaguetza?','Festival en Oaxaca que significa "ofrenda" o "intercambio" en zapoteco',['Un platillo típico de Oaxaca','Un baile ritual veracruzano','Una ceremonia azteca de lluvia']],
['MF','¿Quién es conocido como "Cri Cri", el Grillito Cantor?','Francisco Gabilondo Soler, compositor de música infantil mexicana',['Juan Gabriel','José Alfredo Jiménez','Agustín Lara']],
['MF','¿Cuál es el nombre real de Juan Gabriel?','Alberto Aguilera Valadez',['Juan Gabriel Morales','Alberto Morales Reyes','Juan Alberto Aguilera']],
['MF','¿En qué ocasión se canta "Las Golondrinas"?','Para despedir a alguien',['En los cumpleaños','En la Navidad','En las fiestas patrias']],
['MF','¿Qué canción se canta en los cumpleaños en México?','"Las Mañanitas"',['Las Golondrinas','La Bamba','El Jarabe Tapatío']],
['MF','¿Cuándo es el Día de la Madre en México?','El 10 de mayo',['El segundo domingo de mayo','El primer domingo de mayo','El 8 de mayo']],
['MF','¿Cuándo es el Día de Muertos en México?','El 2 de noviembre',['El 31 de octubre','El 1 de noviembre','El 1 y 2 de noviembre']],
['MF','¿Cuándo es el Día de la Independencia?','El 16 de septiembre',['El 27 de septiembre','El 15 de septiembre','El 5 de mayo']],
['MF','¿Cuándo es el Día de la Revolución?','El 20 de noviembre',['El 16 de septiembre','El 5 de febrero','El 18 de marzo']],
['MF','¿Cuándo es el Día de la Constitución?','El 5 de febrero',['El 20 de noviembre','El 21 de marzo','El 5 de mayo']],
['MF','¿Cuándo es el Día del Trabajo?','El 1 de mayo',['El 5 de mayo','El 15 de mayo','El 21 de marzo']],
['MF','¿Cuándo es el natalicio de Benito Juárez, día festivo?','El 21 de marzo',['El 5 de febrero','El 15 de septiembre','El 1 de mayo']],
['MF','¿Cuál es la flor del Día de Muertos?','El cempasúchil (cempaxóchitl)',['La nochebuena','La dalia','El girasol']],
['MF','¿Qué perro es originario y endémico de México?','El xoloitzcuintle (perro pelón mexicano)',['El chihuahua','El pastor alemán','El pitbull']],
['MF','¿Con qué celebración se asocia "La Catrina"?','Con el Día de Muertos',['Con la Navidad','Con la Independencia','Con la Revolución']],
['MF','¿Quién creó las calaveras artísticas y a La Catrina original?','José Guadalupe Posada',['Diego Rivera','Frida Kahlo','José Clemente Orozco']],
['MF','¿Qué festividad mexicana es Patrimonio Cultural Inmaterial de la UNESCO?','El Día de Muertos',['La Guelaguetza','El Carnaval de Veracruz','Las Posadas navideñas']],
['MF','¿Qué es la Rosca de Reyes?','Un pan en forma de rosca con una figurita de niño adentro, que se come el 6 de enero',['Un dulce típico de Oaxaca','Una piñata navideña','Un platillo de Semana Santa']],
['MF','¿Cuándo comienza el festivo "Maratón Guadalupe-Reyes"?','El 12 de diciembre, Día de la Virgen de Guadalupe',['El 25 de diciembre','El 1 de enero','El 16 de septiembre']],
['MF','¿Cuándo es la festividad de la Virgen de Guadalupe?','El 12 de diciembre',['El 2 de febrero','El 8 de diciembre','El 15 de agosto']],
['MF','¿Qué alimentos son originarios de México?','El chocolate, el aguacate, el jitomate y el guajolote (pavo)',['El trigo, la papa y el maíz','El café, el cacao y el azúcar de caña','El arroz, el trigo y las naranjas']],
['MF','¿Cuál es el ingrediente principal que da sabor al mole?','El chile combinado con chocolate amargo',['La carne de guajolote','El jitomate y la cebolla únicamente','Solo los chiles secos']],
['MF','¿En qué estado mexicano son famosos los 7 moles?','Oaxaca',['Puebla','Guerrero','Michoacán']],
['MF','¿De qué estado son los chiles en nogada?','Puebla',['Oaxaca','Veracruz','Ciudad de México']],
['MF','¿Cuál es la bebida alcohólica típica de México y símbolo nacional?','El tequila',['La cerveza','El mezcal','El pulque']],
['MF','¿De qué planta se obtiene el pulque?','Del maguey (agave)',['Del agave azul','De la tuna','Del nopal']],
['MF','¿Qué bebidas provienen del agave?','El tequila y el mezcal',['El pulque y la cerveza','Solo el tequila','El mezcal y el sotol únicamente']],
['MF','¿Qué es el pozole?','Una sopa de granos de maíz cacahuazintle, típica de México',['Un guiso de res con chile','Una ensalada de frutas tropicales','Un tamal gigante de Veracruz']],
['MF','¿Cuál es la danza típica de Michoacán?','La Danza de los Viejitos',['El Jarabe Tapatío','La Piña','El Venado']],
['MF','¿Cuál es la danza típica de Yucatán?','La Jarana yucateca',['El Son Jarocho','La Piña','Los Voladores']],
['MF','¿Cuál es la danza típica del estado de Sonora?','La Danza del Venado',['El Jarabe Tapatío','La Jarana','La Danza de los Viejitos']],
['MF','¿Cuántos sitios de Patrimonio Mundial de la UNESCO tiene México?','35 sitios (27 culturales y 8 naturales)',['27 sitios','15 sitios','43 sitios']],
['MF','¿Qué es un tamal?','Masa de maíz rellena envuelta en hoja de maíz o plátano, cocida al vapor',['Un pan de trigo típico del norte','Una tortilla de maíz frita','Un postre de arroz con leche']],
['MF','¿Cuál es el platillo típico de Nuevo León?','El cabrito y la machaca',['El mole negro','Los chiles en nogada','La cochinita pibil']],
['MF','¿Cuál es el platillo más representativo de Yucatán?','La cochinita pibil',['El mole negro','El pozole','Los chiles en nogada']],
['MF','¿Cuáles son los versos humorísticos que se escriben en noviembre en honor a los muertos?','Las calaveritas literarias (calaveras)',['Los corridos','Las décimas','Los sones']],
['MF','¿Qué instrumentos son propios del mariachi?','Guitarrón, vihuela, trompeta y violín',['Marimba, guitarra y flauta','Arpa, jarana y jarabe','Tambor, flauta y conch']],
['MF','¿Cuál es la danza prehispánica de Oaxaca conocida como la "Danza de la Pluma"?','La Danza de la Pluma (representa la Conquista)',['Los Voladores de Papantla','La Danza del Venado','El Jarabe Tapatío']],
['MF','¿Qué bebida fermentada sagrada bebían los aztecas?','El pulque',['El tequila','El mezcal','El octli de agave azul']],
['MF','¿Qué es el "Día de Reyes" y cuándo se celebra?','El 6 de enero, se celebra la llegada de los Reyes Magos y se parte la Rosca de Reyes',['El 25 de diciembre','El 12 de diciembre','El 2 de noviembre']],
['MF','¿De dónde es la cochinita pibil?','Yucatán',['Campeche','Tabasco','Chiapas']],
['MF','¿Qué cantante mexicano es conocido como el "Divo de Juárez"?','Juan Gabriel',['Vicente Fernández','José Alfredo Jiménez','Agustín Lara']],
['MF','¿Cuándo se celebra el Día de la Bandera en México?','El 24 de febrero',['El 16 de septiembre','El 5 de febrero','El 1 de enero']],
['MF','¿Qué evento religioso se celebra en Iztapalapa, Ciudad de México, el Viernes Santo?','La representación de la Pasión de Cristo, la más grande de México',['La peregrinación a la Basílica de Guadalupe','El Día de Muertos','Las Posadas navideñas']],
['MF','¿Qué postre es típico de Guanajuato?','Las charamuscas',['La jericalla','La cajeta de Celaya... ambas son de Guanajuato','El dulce de leche']],
['MF','¿Qué es la cajeta?','Un dulce de leche de cabra quemada, típico de Celaya, Guanajuato',['Un helado de frutas','Una bebida alcohólica','Un pan dulce tradicional']],
['MF','¿Cuál es el postre típico de Guadalajara?','La jericalla (parecida al flan)',['La cajeta','Las charamuscas','Las palanquetas']],
['MF','¿Cuándo se celebra el Día del Padre en México?','El tercer domingo de junio',['El primer domingo de junio','El 19 de marzo','El segundo domingo de junio']],
['MF','¿Qué es el aguardiente de agave llamado mezcal?','Bebida alcohólica destilada del agave, producida en varias regiones de México (especialmente Oaxaca)',['Solo tequila de otra región','Una cerveza de agave','Una bebida de pulque destilado']],

// ── NUEVAS PREGUNTAS — Guía Intensiva SRE (agregadas automáticamente) ────────

// Datos Generales y Símbolos
['GS','¿Cuál es la moneda oficial de México?','El peso mexicano',['El dólar','El euro','El quetzal']],
['GS','¿Qué representa el águila devorando una serpiente en el escudo nacional?','La fundación de México-Tenochtitlán según la leyenda mexica',['La victoria en la Batalla de Puebla','El triunfo sobre los españoles','El inicio de la Revolución Mexicana']],
['GS','¿Cuál es el idioma con mayor número de hablantes en México?','El español',['El náhuatl','El maya','El inglés']],
['GS','¿Qué ave aparece en el escudo nacional de México?','El águila real',['El cóndor','El halcón','El búho']],
['GS','¿Cuál es la capital de la República Mexicana?','Ciudad de México',['Guadalajara','Monterrey','Puebla']],
['GS','¿Cuántos estados tiene la República Mexicana?','32 estados',['28 estados','31 estados','33 estados']],

// Época Prehispánica
['PH','¿Qué civilización construyó Chichén Itzá?','La civilización maya',['La olmeca','La tolteca','La mexica']],
['PH','¿En qué península se desarrolló principalmente la cultura maya?','En la Península de Yucatán',['En la Península de Baja California','En la Sierra Madre','En el Valle de México']],
['PH','¿Quién gobernaba a los mexicas cuando llegó Hernán Cortés?','Moctezuma II (Moctezuma Xocoyotzin)',['Cuauhtémoc','Cuitláhuac','Nezahualcóyotl']],
['PH','¿Dónde se encuentra la zona arqueológica de Chichén Itzá?','En el estado de Yucatán',['En Jalisco','En Sonora','En Chiapas']],

// Independencia
['IN','¿Quién consumó la Independencia de México?','Agustín de Iturbide, al mando del Ejército Trigarante',['Benito Juárez','Venustiano Carranza','Francisco I. Madero']],
['IN','¿En qué ciudad se proclamó el Grito de Dolores?','En Dolores Hidalgo, Guanajuato',['En Querétaro','En Puebla','En Morelia']],

// Revolución
['RE','¿En qué siglo ocurrió el Porfiriato?','En el siglo XIX (y principios del XX)',['En el siglo XVIII','En el siglo XXI','En el siglo XVII']],
['RE','¿Quién promulgó la Constitución de 1917?','Venustiano Carranza',['Pancho Villa','Emiliano Zapata','Plutarco Elías Calles']],
['RE','¿Quién escribió el Plan de San Luis Potosí que convocó a la Revolución?','Francisco I. Madero',['Emiliano Zapata','Pancho Villa','Álvaro Obregón']],
['RE','¿Quién lideró la famosa División del Norte durante la Revolución?','Francisco (Pancho) Villa',['Emiliano Zapata','Venustiano Carranza','Plutarco Elías Calles']],

// Geografía
['GT','¿Cuál es el océano que baña la costa oeste (Pacífico) de México?','El Océano Pacífico',['El Océano Atlántico','El Mar Caribe','El Mar Índico']],
['GT','¿Cuál es el estado más grande por superficie en México?','Chihuahua',['Sonora','Jalisco','Durango']],

// Civismo y Gobierno
['CG','¿Cuántos poderes tiene la Unión en México?','Tres: Ejecutivo, Legislativo y Judicial',['Dos','Cuatro','Cinco']],
['CG','¿Cada cuántos años se elige al Presidente de México?','Cada 6 años (sin reelección)',['Cada 4 años','Cada 5 años','Cada 8 años']],
['CG','¿Cuál es la cámara alta del Congreso mexicano?','El Senado de la República',['La Cámara de Diputados','La Suprema Corte','El INE']],
['CG','¿Quién encabeza el Poder Ejecutivo Federal en México?','El Presidente de la República',['El Senado','La Suprema Corte','Los gobernadores']],

// Ciencia y Educación
['CE','¿Qué significa la sigla SEP?','Secretaría de Educación Pública',['Sistema Educativo Público','Servicio Escolar Público','Secretaría Estatal Pedagógica']],
['CE','¿Cuál es la universidad más grande de México?','La UNAM (Universidad Nacional Autónoma de México)',['El IPN','La UAM','El ITESM (Tecnológico de Monterrey)']],

// Literatura y Arte
['LA','¿Quién escribió la novela "Pedro Páramo"?','Juan Rulfo',['Carlos Fuentes','Octavio Paz','Jaime Sabines']],
['LA','¿Qué obra pictórica es famosa de Frida Kahlo?','Sus autorretratos (self-portraits)',['Los murales del Palacio Nacional','La Piedad','El sueño de una tarde dominical']],

// Música, Fiestas y Comida
['MF','¿De qué estado es originario el mole poblano?','De Puebla',['De Oaxaca','De Jalisco','De Veracruz']],
['MF','¿Qué género musical es considerado símbolo de México ante la UNESCO?','El mariachi',['La cumbia','El tango','El flamenco']],
['MF','¿Qué celebran los mexicanos el Día de Muertos (2 de noviembre)?','La memoria y el recuerdo de los difuntos',['La Independencia de México','El inicio de la Revolución','El Año Nuevo']],
['MF','¿Qué se celebra el 16 de septiembre en México?','El aniversario del inicio de la Guerra de Independencia (Grito de Dolores, 1810)',['El fin de la Revolución Mexicana','La promulgación de la Constitución','El Día del Trabajo']],
];

// Build question objects with id
const questions = RAW.map((r, i) => ({
  id: i,
  cat: r[0],
  q: r[1],
  a: r[2],
  wrong: r[3],
}));

console.log(`✅ ${questions.length} preguntas cargadas en ${Object.keys(CATS).length} categorías`);
